services:
  db:
    image: postgres:15
    container_name: ironforge-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DB
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ironforge-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ironforge.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - '8080:80'
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  neo4j:
    image: neo4j:5.25
    container_name: ironforge-neo4j
    environment:
      - NEO4J_AUTH=neo4j/test1234  # username/password
    ports:
      - "7474:7474"   # HTTP browser
      - "7687:7687"   # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
    restart: unless-stopped

  scheduler:
    platform: linux/amd64
    container_name: ironforge-scheduler
    depends_on:
      db:
        condition: service_healthy
    build: 
      context: ./ironforge-scheduler-service
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=DB
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import: